[project]
authors = ["Min RK <benjaminrk@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "mumps-test"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
pip = ">=24.2,<25"
mpi = { version = "*", build = "mpich" }


[feature.before.dependencies]
mumps-seq = { version = "==5.7.3", build = "*_2" }
mumps-mpi = { version = "==5.7.3", build = "*_2" }

[feature.omp.dependencies]
mumps-seq = { version = "==5.7.3", build = "*_3" }
mumps-mpi = { version = "==5.7.3", build = "*_3" }

[feature.gemmt]
channels = [{channel = "minrk/label/mumps-gemmt", priority = 1}, "conda-forge"]

[feature.gemmt.dependencies]
mumps-seq = { version = "==5.7.3", build = "*_104" }
mumps-mpi = { version = "==5.7.3", build = "*_104" }

[feature.openblas.dependencies]
blas = { version = "*", build = "*openblas" }

[feature.mkl]
platforms = ["linux-64"]

[feature.mkl.dependencies]
blas = { version = "*", build = "*mkl" }


[feature.fenics.dependencies]
fenics-dolfinx = "0.8.0"
wurlitzer = ">=3.1.1"

[feature.python-mumps.dependencies]
python-mumps = "*"
scipy = "*"

[environments]
before-openblas = ["fenics", "python-mumps", "before", "openblas"]
omp-openblas = ["fenics", "python-mumps", "omp", "openblas"]
gemmt-openblas = ["fenics", "python-mumps", "gemmt", "openblas"]
before-mkl = ["fenics", "python-mumps", "before", "mkl"]
omp-mkl = ["fenics", "python-mumps", "omp", "mkl"]
gemmt-mkl = ["fenics", "python-mumps", "gemmt", "mkl"]
