[project]
name = "fenics-omp-mkl"
channels = ['conda-forge']
platforms = ['linux-64']

[dependencies]
python = "3.12.*"
pip = ">=24.2,<25"
blas = { version = "*", build = "*mkl" }
fenics-dolfinx = ">=0.8.0,<0.9"
mpich = ">=4.2.2,<5"
wurlitzer = ">=3.1.1,<4"
mumps-mpi = { version = "==5.7.3", build = "*_3" }
