[project]
name = "fenics-omp-openblas"
channels = ['conda-forge']
platforms = ['linux-64', 'osx-arm64']

[dependencies]
python = "3.12.*"
pip = ">=24.2,<25"
blas = { version = "*", build = "*openblas" }
fenics-dolfinx = ">=0.8.0,<0.9"
mpich = ">=4.2.2,<5"
wurlitzer = ">=3.1.1,<4"
mumps-mpi = { version = "==5.7.3", build = "*_2" }
